block-whitelist : [IRON_BLOCK, IRON_INGOT, IRON_SWORD, IRON_BOOTS, IRON_CHESTPLATE, IRON_LEGGINGS, IRON_HELMET,
                   OAK_LOG, OAK_PLANKS, OAK_BUTTON,
                   DIAMOND_BLOCK, DIAMOND, DIAMOND_PICKAXE, DIAMOND_SWORD, DIAMOND_CHESTPLATE, DIAMOND_LEGGINGS, DIAMOND_BOOTS, DIAMOND_HELMET
                  ]
required-player-count : 1
start-countdown : 5
respawn-delay : 5
return-to-lobby-delay : 60
spawn-protection-distance : 5
std-colors :
  std-red : "255,66,66"
  std-blue : "61,58,232"
  std-yellow : "255,246,82"
  std-gray : "112,112,112"
  std-green : "70,207,77"

armor : ["LEATHER_BOOTS", "LEATHER_LEGGINGS", "LEATHER_CHESTPLATE", "LEATHER_HELMET"]
hotbar :
  STONE_SWORD: 1
  IRON_PICKAXE : 1
  OAK_LOG: 16