whitelist-break : []
whitelist-craft : []
required-player-count : 2
start-countdown : 15
respawn-delay : 5
return-to-lobby-delay : 120

armor : ["LEATHER_BOOTS", "LEATHER_LEGGINGS", "LEATHER_CHESTPLATE", "LEATHER_HELMET"]
inventory : ["STONE_SWORD"]