name: Bedwars
version: '${version}'
main: eu.cosup.bedwars.Bedwars
api-version: 1.19
depend:
  - "Tournament"
commands:
  spectate:
    aliases: [sp]
  forcestart:
    aliases: [fs]
  generator:
    aliases: [gen]
  openshop:
    aliases: [os]
  openupgrades:
    aliases: [ou]